# Generated by Django 3.2.7 on 2022-01-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golbal_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=250)),
                ('is_registered', models.BooleanField(default=False)),
                ('spam', models.IntegerField(default=0)),
            ],
        ),
    ]
