# Generated by Django 3.2.7 on 2022-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_golbal_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='golbal_users',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
