# Generated by Django 3.2.7 on 2022-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_golbal_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golbal_users',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
